### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by bibiana-m** [SistemasTecTlaxiaco/infografia-bibiana-m#2]
[infografia de los sistemas numericos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-bibiana-m/files/12591179/infografia.de.los.sistemas.numericos.pdf)

**Comment by Alberto796** [comment]
REDACCION: 10/4%
exposición de ideas: 15/13%
organizacion de la informacion: 15/13%
uso de imagenes: 15/15%
presentacion visual: 15/13%
referencias: 15/9%
presentacion:15/11%
calificacion: 16
calificado por el equipo de Jose Antonio Rodrigez Cruz "37"

**Comment by josealfredo79** [comment]
@Alberto796 falta la calificacion no mayor de 20 por favor

**Comment by josealfredo79** [comment]
Nuevamente falta la calificacion

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
